version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ".env"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "${APP_ROOT}:/var/www/html"
    depends_on:
      - php
      - mysql

  php:
    build: ./docker/php/
    restart: always
    env_file:
      - ".env"
    volumes:
      - "${APP_ROOT}:/var/www/html"

  composer:
    image: "composer"
    env_file:
      - ".env"
    volumes:
      - "${APP_ROOT}:/app"
    command: install

  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
